### ISSUE TITLE
highlighting of source code

### ISSUE THREAD

**Issue by pnathan** [articulate-common-lisp/articulate-common-lisp.github.io#11]
The source code right now just refers to raw code. It would be nice if syntax highlighted versions of this source existed.

**Comment by mordocai** [comment]
Assuming https://truongtx.me/2012/12/28/jekyll-bootstrap-syntax-highlighting/ is still up to date enough pygments doesn't sound too hard to get set up and works really well in my experience. I'll work on this next time I have a chance.

**Comment by vindarel** [comment]
done with highlight-lisp again: https://github.com/orthecreedence/highlight-lisp

it respects non-lisp code.

![selection_160](https://user-images.githubusercontent.com/3721004/27564553-c2cbb66c-5ad8-11e7-9f05-c345a2a6597f.png)

done ! :)

**Comment by pnathan** [comment]
@vindarel I await the PR

**Comment by vindarel** [comment]
woops :) https://github.com/articulate-common-lisp/articulate-common-lisp.github.io/pull/64
