### ISSUE TITLE
Do we really have to write html ? Where to write content ?

### ISSUE THREAD

**Issue by vindarel** [articulate-common-lisp/articulate-common-lisp.github.io#56]
Hi,
finally I got quicklisp and slime working, thanks to this website :)
I forked this repo. It's done with Jekyll. But I can't find markdown content. Nor can I find a "gh-pages" branch. Where the heck can I find the content files ? I see html files with a yaml frontend… do we have to write html ?

thanks

**Comment by pnathan** [comment]
Hi there,

This has been hanging idle for a bit, and I can't remember anymore. Let me
get back to you in another 8 hours or so.

**Comment by pnathan** [comment]
Sorry about the delay. Family stuff... anyway.  

-The site is being run off of a ec2 node I run a few other sites on.  Publishes involve "slap pnathan and tell him to update it". Part of the rationale involved running a Hunchentoot server once upon a time. Legggacy. 

- Looks like I did indeed go for HTML. I'm *sure* I had a good reason, once. :sigh: Possibly the reason involved, "I don't want to fart with jekyll overly much and I have very limited time"... that seems to stick in my recollection. Some slapping of pnathan may be in order there.

**Comment by vindarel** [comment]
> Some slapping of pnathan may be in order there.

nooo :D 

So looks like we agree pure html isn't a panacea. So the first one to propose a markdown solution will receive a big thank you. I know what to do when I get bored at christmas.

Maybe work will be saved by the possibility to mix markdown and html. That would be great, we may have only to restructure the website and write a new build command. We may not have a lot of work. Building a Jekyll site isn't difficult.

I also discovered Cliki but your website has value.
Btw I discovered [Portacle](https://shinmera.github.io/portacle/), a portable and multiplatform lisp environment: sbcl, quicklisp, emacs, slime and git. Easy ! (could you add it ?)

see you !

**Comment by pnathan** [comment]
I haven't encountered portacle before. Is it easy to use? My perspective is
very skewed at this point, I've been Lisping/emacsing/version controlling
for almost a decade now, so my judgements are a bit experience-skewed.

**Comment by vindarel** [comment]
Yes it looks like working perfectly on linux and windows, except latest version of Mac: https://www.reddit.com/r/lisp/comments/5j2fek/portacle_a_portable_common_lisp_development/

**Comment by pnathan** [comment]
great.

I'll try to force open my evening tonight to do a deploy here, then I'll examine how the deploy strategy is to automate it more.

**Comment by pnathan** [comment]
@vindarel this is now published on github pages via the `master` branch; the dns system is appropriately configured, with the usual DNS records trickling out across the globe to different nameservers.  There's a metric ton of cruft hanging out in the repo, and certainly it's worth chasing down and removing at some point. 

I've merged your PRs. Please feel free to decruftify. I don't know if I'll be very active here for a bit, I have a very busy month coming up (the past 2 months have involved a lot of high priority family stuff), and then I'll be back at work.

**Comment by vindarel** [comment]
Yeah, cool, nice job !

> feel free to decruftify

ok, I'll keep learning and see what can be improved.

See you !
