### ISSUE TITLE
Reading a text file snippet is too convoluted ?

### ISSUE THREAD

**Issue by vindarel** [articulate-common-lisp/articulate-common-lisp.github.io#71]
Indeed, it turns out we have uiop at help:

    (uiop:read-file-string "file.txt")

or read-file-lines,

when your snippet is longer (http://articulate-lisp.com/examples/snippets.html, bottom)

**Comment by pnathan** [comment]
I've generally avoided directly relying on libraries - in Snippets, it's aimed to be partially showing the way of lisp. But perhaps that's not ideal and the uiop alternative should be presented as well?
